
import { GlassCard } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Gavel, Info, Zap, CheckCircle } from "lucide-react";
import { StatusBadge } from "@/components/ui/status-badge";

interface DealCardProps {
    price: number;
    weight: string;
    total: number;
    isOfficial?: boolean;
    onAccept?: () => void;
    onCounter?: () => void;
}

export function DealCard({ price, weight, total, isOfficial = true, onAccept, onCounter }: DealCardProps) {
    return (
        <div className="relative w-full max-w-sm group">
            <div className="absolute -inset-1 bg-gradient-to-r from-primary to-green-600 rounded-2xl opacity-20 blur transition duration-1000 group-hover:opacity-100 group-hover:duration-200" />
            <GlassCard className="relative p-0 overflow-hidden border-primary/30 shadow-2xl bg-surface-darker">
                <div className="bg-primary/10 border-b border-primary/20 p-4 flex justify-between items-center">
                    <div className="flex items-center gap-2 text-primary font-bold text-xs uppercase tracking-widest">
                        <Gavel size={14} /> Proposed Offer
                    </div>
                    {isOfficial && <StatusBadge variant="primary" className="text-[8px] bg-primary/20">Official Bid</StatusBadge>}
                </div>
                <div className="p-6 space-y-6">
                    <div className="flex justify-between items-end">
                        <div>
                            <p className="text-[10px] text-gray-500 uppercase tracking-widest mb-1 font-bold">Price per Kg</p>
                            <p className="text-4xl font-bold text-white">${price.toFixed(2)}<span className="text-lg text-gray-500 font-normal ml-1">/kg</span></p>
                        </div>
                        <div className="text-right">
                            <p className="text-[10px] text-gray-500 uppercase tracking-widest mb-1 font-bold">Total Est.</p>
                            <p className="text-2xl font-bold text-emerald-400">${total.toFixed(2)}</p>
                            <p className="text-[10px] text-gray-500 font-medium">for {weight} net</p>
                        </div>
                    </div>

                    <div className="bg-background-dark/50 rounded-xl p-3 border border-white/5 flex gap-3 items-start">
                        <Info size={14} className="text-yellow-500 mt-0.5 shrink-0" />
                        <p className="text-[10px] text-gray-400 leading-relaxed">
                            Condition: Subject to physical verification upon delivery. <br />
                            Payment Terms: Instant via Stripe/UPI.
                        </p>
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                        <Button variant="secondary" className="h-11 text-xs font-bold border-white/10" onClick={onCounter}>
                            <span className="mr-2">✎</span> Counter
                        </Button>
                        <Button className="h-11 text-xs font-bold shadow-glow-primary hover:bg-green-400 text-background-dark" onClick={onAccept}>
                            <CheckCircle size={16} className="mr-2" /> Accept Deal
                        </Button>
                    </div>
                </div>
                <div className="bg-background-dark p-2 text-center border-t border-white/5">
                    <p className="text-[8px] text-gray-600 flex items-center justify-center gap-1 font-medium">
                        <Zap size={8} className="text-primary" /> Generated by UrbanMine AI Broker
                    </p>
                </div>
            </GlassCard>
        </div>
    );
}
